#%RAML 1.0
title: employee-experience-api
version: v1
baseUri: http://localhost:8081/api

mediaType: application/xml

types:
  Employees:
    type: object
    properties:
      employee:
        type: array
        items:
          type: object
          properties:
            employeeId: integer
            employeeName: string
            companyName: string
            dateOfJoin: datetime
            salary: number
            address: string
            projects: string

/employees-bulk-insert:
  post:
    description: Accepts bulk employee data in XML (max 10)
    body:
      application/xml:
        type: Employees
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": "Employee data accepted successfully"
              }
      400:
        body:
          application/json:
            example:
              {
                "message": "Only up to 10 employee records are allowed"
              }